version: '3'
services:

  mysql_db:
    image: mysql:5.7
    environment:   
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Facebook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-tier

  python_facebook_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    networks:
      - app-tier
    command:
      tail -f /dev/null
    networks:
      app-tier:
      driver: bridge
  connect:
    build:
      context: .
      dockerfile: Dockerfile2
    depends_on:
      - python_facebook_app
    networks:
      - app-tier
    command:
      tail -f /dev/null
    networks:
      app-tier:
      driver: bridge
